//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36315
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDSAC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDSAC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuota Número.
        /// </summary>
        internal static string EXTRA_PAY_NUMBER {
            get {
                return ResourceManager.GetString("EXTRA_PAY_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string EXTRA_PAY_VALUE {
            get {
                return ResourceManager.GetString("EXTRA_PAY_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string FINANCING_PLAN_DESC {
            get {
                return ResourceManager.GetString("FINANCING_PLAN_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string FINANCING_PLAN_ID {
            get {
                return ResourceManager.GetString("FINANCING_PLAN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de creación.
        /// </summary>
        internal static string FinancingPlanCreation_date {
            get {
                return ResourceManager.GetString("FinancingPlanCreation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porc.Int..
        /// </summary>
        internal static string FinancingPlanDefault_interest_perc {
            get {
                return ResourceManager.GetString("FinancingPlanDefault_interest_perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financia IVA.
        /// </summary>
        internal static string FinancingPlanDeferred_tax {
            get {
                return ResourceManager.GetString("FinancingPlanDeferred_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro.Cuotas Vencidas para Suspensión.
        /// </summary>
        internal static string FinancingPlanDuedate_acc_count_susp {
            get {
                return ResourceManager.GetString("FinancingPlanDuedate_acc_count_susp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro. Cuotas Venc. para Translado.
        /// </summary>
        internal static string FinancingPlanDuedate_acc_count_tr {
            get {
                return ResourceManager.GetString("FinancingPlanDuedate_acc_count_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Final.
        /// </summary>
        internal static string FinancingPlanEnd_date_apply {
            get {
                return ResourceManager.GetString("FinancingPlanEnd_date_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de Cálculo.
        /// </summary>
        internal static string FinancingPlanFin_compute_meth {
            get {
                return ResourceManager.GetString("FinancingPlanFin_compute_meth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor Gra..
        /// </summary>
        internal static string FinancingPlanGradient_factor {
            get {
                return ResourceManager.GetString("FinancingPlanGradient_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Ini..
        /// </summary>
        internal static string FinancingPlanInitial_date_apply {
            get {
                return ResourceManager.GetString("FinancingPlanInitial_date_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa de Interés.
        /// </summary>
        internal static string FinancingPlanInterest_rate {
            get {
                return ResourceManager.GetString("FinancingPlanInterest_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máx.Nro.Cuot.Ext..
        /// </summary>
        internal static string FinancingPlanMax_extra_payments {
            get {
                return ResourceManager.GetString("FinancingPlanMax_extra_payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porc.Mín.Deud.Canc..
        /// </summary>
        internal static string FinancingPlanMin_debt_cancel_perc {
            get {
                return ResourceManager.GetString("FinancingPlanMin_debt_cancel_perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porc.Cuo.Ini..
        /// </summary>
        internal static string FinancingPlanRange_init_pay_percent {
            get {
                return ResourceManager.GetString("FinancingPlanRange_init_pay_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porc.Fin..
        /// </summary>
        internal static string FinancingPlanRange_percent_to_finan {
            get {
                return ResourceManager.GetString("FinancingPlanRange_percent_to_finan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro.Cuotas.
        /// </summary>
        internal static string FinancingPlanRange_quotas_number {
            get {
                return ResourceManager.GetString("FinancingPlanRange_quotas_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos Ad..
        /// </summary>
        internal static string FinancingPlanRange_spread {
            get {
                return ResourceManager.GetString("FinancingPlanRange_spread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc.Soporte.
        /// </summary>
        internal static string FinancingPlanSupport_document {
            get {
                return ResourceManager.GetString("FinancingPlanSupport_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro.Veces Refinan..
        /// </summary>
        internal static string FinancingPlanTimes_to_refinance {
            get {
                return ResourceManager.GetString("FinancingPlanTimes_to_refinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato?.
        /// </summary>
        internal static string FinancingPlanWarranty_generate {
            get {
                return ResourceManager.GetString("FinancingPlanWarranty_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionario.
        /// </summary>
        internal static string NAME_ {
            get {
                return ResourceManager.GetString("NAME_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido una excepción inesperada en la aplicación.
        /// </summary>
        internal static string NOTCONTROLEDERRORDESC {
            get {
                return ResourceManager.GetString("NOTCONTROLEDERRORDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAYSTOFIRSTPAY.
        /// </summary>
        internal static string ParameterDAYSTOFIRSTPAY {
            get {
                return ResourceManager.GetString("ParameterDAYSTOFIRSTPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINAN_PREFIX_OUTFILE.
        /// </summary>
        internal static string ParameterFINAN_PREFIX_OUTFILE {
            get {
                return ResourceManager.GetString("ParameterFINAN_PREFIX_OUTFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FININCINTERESTPERC.
        /// </summary>
        internal static string ParameterFININCINTERESTPERC {
            get {
                return ResourceManager.GetString("ParameterFININCINTERESTPERC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FININCPERCINITPAY.
        /// </summary>
        internal static string ParameterFININCPERCINITPAY {
            get {
                return ResourceManager.GetString("ParameterFININCPERCINITPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FININCPERCTOFINANC.
        /// </summary>
        internal static string ParameterFININCPERCTOFINANC {
            get {
                return ResourceManager.GetString("ParameterFININCPERCTOFINANC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FININCQUOTASNUMBER.
        /// </summary>
        internal static string ParameterFININCQUOTASNUMBER {
            get {
                return ResourceManager.GetString("ParameterFININCQUOTASNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FININCSPREAD.
        /// </summary>
        internal static string ParameterFININCSPREAD {
            get {
                return ResourceManager.GetString("ParameterFININCSPREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        internal static string PRODUCT_ID {
            get {
                return ResourceManager.GetString("PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Producto.
        /// </summary>
        internal static string PRODUCT_TYPE {
            get {
                return ResourceManager.GetString("PRODUCT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total financiable seleccionado.
        /// </summary>
        internal static string TXTFINANCIABLESELECT {
            get {
                return ResourceManager.GetString("TXTFINANCIABLESELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De los productos seleccionados: No financiable + Conceptos financiables no seleccionados.
        /// </summary>
        internal static string TXTMINVALUETOPAYPRODSEL {
            get {
                return ResourceManager.GetString("TXTMINVALUETOPAYPRODSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del total de la suscripción: No financiable + Financiable no seleccionado.
        /// </summary>
        internal static string TXTMINVALUETOPAYSUBSCRIP {
            get {
                return ResourceManager.GetString("TXTMINVALUETOPAYSUBSCRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total no financiable de productos seleccionados.
        /// </summary>
        internal static string TXTNOTFINBALANCESELPRODUCT {
            get {
                return ResourceManager.GetString("TXTNOTFINBALANCESELPRODUCT", resourceCulture);
            }
        }
    }
}
